using LawyerWebSite.Entities.Concretes;
using LawyerWebSite.Entities.Concretes.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Text;

namespace LawyerWebSite.DataAccess.Concretes.EntityFrameworkCore.Mapping
{
    public class ArticleMap : IEntityTypeConfiguration<Article>
    {
        public void Configure(EntityTypeBuilder<Article> builder)
        {
            builder.Property(a => a.Title).HasMaxLength(175).IsRequired();
            builder.Property(a => a.Content).HasColumnType("nvarchar(max)").IsRequired();

            builder.HasData(
                new Article { Id = 1, CategoryId = 1, Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent aliquam sem non odio commodo consectetur. Curabitur sem nunc, maximus sed odio a, faucibus ullamcorper nisl. Fusce in neque turpis. Fusce eget sapien non nibh suscipit eleifend. Nullam enim tortor, laoreet in scelerisque ac, facilisis in nibh. Nulla facilisi. Donec ultricies porttitor rhoncus. Nam ut eros suscipit, aliquam magna eget, gravida turpis. Aenean varius neque lectus, eget mollis orci accumsan non. Suspendisse sodales dui nulla. Mauris et diam quis mauris commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent aliquam sem non odio commodo consectetur. Curabitur sem nunc, maximus sed odio a, faucibus ullamcorper nisl. Fusce in neque turpis. Fusce eget sapien non nibh suscipit eleifend. Nullam enim tortor, laoreet in scelerisque ac, facilisis in nibh. Nulla facilisi. Donec ultricies porttitor rhoncus. Nam ut eros suscipit, aliquam magna eget, gravida turpis. Aenean varius neque lectus, eget mollis orci accumsan non. Suspendisse sodales dui nulla. Mauris et diam quis mauris commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent aliquam sem non odio commodo consectetur. Curabitur sem nunc, maximus sed odio a, faucibus ullamcorper nisl. Fusce in neque turpis. Fusce eget sapien non nibh suscipit eleifend. Nullam enim tortor, laoreet in scelerisque ac, facilisis in nibh. Nulla facilisi. Donec ultricies porttitor rhoncus. Nam ut eros suscipit, aliquam magna eget, gravida turpis. Aenean varius neque lectus, eget mollis orci accumsan non. Suspendisse sodales dui nulla. Mauris et diam quis mauris commodo consequat", Url = "Lorem-ipsum-dolor-sit-amet", Picture = "ceza-hukuku.jpeg", Title = "Lorem Ipsum Dolor Sit Amet"},
                 new Article { Id = 2, CategoryId = 2, Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent aliquam sem non odio commodo consectetur. Curabitur sem nunc, maximus sed odio a, faucibus ullamcorper nisl. Fusce in neque turpis. Fusce eget sapien non nibh suscipit eleifend. Nullam enim tortor, laoreet in scelerisque ac, facilisis in nibh. Nulla facilisi. Donec ultricies porttitor rhoncus. Nam ut eros suscipit, aliquam magna eget, gravida turpis. Aenean varius neque lectus, eget mollis orci accumsan non. Suspendisse sodales dui nulla. Mauris et diam quis mauris commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent aliquam sem non odio commodo consectetur. Curabitur sem nunc, maximus sed odio a, faucibus ullamcorper nisl. Fusce in neque turpis. Fusce eget sapien non nibh suscipit eleifend. Nullam enim tortor, laoreet in scelerisque ac, facilisis in nibh. Nulla facilisi. Donec ultricies porttitor rhoncus. Nam ut eros suscipit, aliquam magna eget, gravida turpis. Aenean varius neque lectus, eget mollis orci accumsan non. Suspendisse sodales dui nulla. Mauris et diam quis mauris commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent aliquam sem non odio commodo consectetur. Curabitur sem nunc, maximus sed odio a, faucibus ullamcorper nisl. Fusce in neque turpis. Fusce eget sapien non nibh suscipit eleifend. Nullam enim tortor, laoreet in scelerisque ac, facilisis in nibh. Nulla facilisi. Donec ultricies porttitor rhoncus. Nam ut eros suscipit, aliquam magna eget, gravida turpis. Aenean varius neque lectus, eget mollis orci accumsan non. Suspendisse sodales dui nulla. Mauris et diam quis mauris commodo consequat", Url = "Lorem-ipsum-dolor-sit-amet-2", Picture = "tazminat-hukuku.jpeg", Title = "Lorem Ipsum Dolor Sit Amet"},
                  new Article { Id = 3, CategoryId = 3, Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent aliquam sem non odio commodo consectetur. Curabitur sem nunc, maximus sed odio a, faucibus ullamcorper nisl. Fusce in neque turpis. Fusce eget sapien non nibh suscipit eleifend. Nullam enim tortor, laoreet in scelerisque ac, facilisis in nibh. Nulla facilisi. Donec ultricies porttitor rhoncus. Nam ut eros suscipit, aliquam magna eget, gravida turpis. Aenean varius neque lectus, eget mollis orci accumsan non. Suspendisse sodales dui nulla. Mauris et diam quis mauris commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent aliquam sem non odio commodo consectetur. Curabitur sem nunc, maximus sed odio a, faucibus ullamcorper nisl. Fusce in neque turpis. Fusce eget sapien non nibh suscipit eleifend. Nullam enim tortor, laoreet in scelerisque ac, facilisis in nibh. Nulla facilisi. Donec ultricies porttitor rhoncus. Nam ut eros suscipit, aliquam magna eget, gravida turpis. Aenean varius neque lectus, eget mollis orci accumsan non. Suspendisse sodales dui nulla. Mauris et diam quis mauris commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent aliquam sem non odio commodo consectetur. Curabitur sem nunc, maximus sed odio a, faucibus ullamcorper nisl. Fusce in neque turpis. Fusce eget sapien non nibh suscipit eleifend. Nullam enim tortor, laoreet in scelerisque ac, facilisis in nibh. Nulla facilisi. Donec ultricies porttitor rhoncus. Nam ut eros suscipit, aliquam magna eget, gravida turpis. Aenean varius neque lectus, eget mollis orci accumsan non. Suspendisse sodales dui nulla. Mauris et diam quis mauris commodo consequat", Url = "Lorem-ipsum-dolor-sit-amet-2", Picture = "medeni-hukuk.jpeg", Title = "Lorem Ipsum Dolor Sit Amet"}

                );
        }
    }
}
